### PR TITLE
Cleanup invisibles

### PR DESCRIPTION
**Pull request by lxxxvi**
Hi 👋 

This PR is a simple cleanup task:

* Replaces non-breaking spaces with regular ones
* Removes empty lines
* Removes trailing white spaces

Also, I was wondering what part `prettier` plays in the project? For example: Many files of the project use single quotes although the configuration in `.prettierrc.json` says 

```json
"singleQuote": false,
```

(Short: My editor keeps replacing the quotes automatically... 😄)

### CODE REVIEW

**Review by marcoroth — APPROVED** [review]
Thank you for opening this pull request @lxxxvi!

I love how consistently it used non-breaking spaces throughout almost occurrences of `executeStream` 🙃 


I think part of the problem is that prettier is only setup to lint TypeScript .ts files and not the JavaScript .js within the test/ directory.

Maybe we could also change that? Otherwise I'm also happy to merge this as-is.

**Comment by marcoroth** [comment]
Or I should say eslint (which uses prettier as a plugin):

https://github.com/marcoroth/turbo_power/blob/87c667a60c14f9cae2b6e8c6bc59d0daf000fa26/package.json#L22

**Comment by lxxxvi** [comment]
@marcoroth I think something is not right with the eslint setup either, but I have no experience there. Should/could we have look at it together?

**Comment by marcoroth** [comment]
@lxxxvi let's do that in a separate PR so we can merge this one,  thank you! 🎉

**Pull request merged**
